version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/santex_test
    ports:
      - 5000:5000

# version: '3.8'

# services:
#   web:
#     build: .
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/my_flask_app
#     environment:
#       - FLASK_ENV=development
#       - FLASK_APP=run.py
#     depends_on:
#       - db
#   db:
#     image: postgres:13
#     environment:
#       - POSTGRES_DB=mydatabase
#       - POSTGRES_USER=myuser
#       - POSTGRES_PASSWORD=mypassword
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

