version: '3.8'

services:
  app:
    build: .
    environment:
      - API_TOKEN=${API_TOKEN}
      - MONGO_URI=mongodb://mongo:27017/santex_test # Setting the URI for MongoDB
    volumes:
      - .:/santex_test
    ports:
      - 5000:5000
    depends_on:
      - mongo # Ensure that the app starts after MongoDB

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017 # Expose MongoDB's port so you can connect to it externally
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
